query MyQuery {
    recipe {
        slug
        id
        excerpt
        description {
            value
        }
        ingredientsItems {
            id
            name
        }
        ingredientsText {
            blocks
            links
            value
        }
        title
    }
}
