query recipes {
  recipeModel {
    id
    description {
      blocks
    }
    excerpt
    featuredImage {
      height
      width
    }
    ingredientsItems {
      id
      name
    }
    vegetarian
    title
    slug
    ingredientsText {
      blocks
    }
  }
}
