schema: ./generated/datocms-schema.graphql
extensions:
  endpoints:
    DatoCMS Graphql Endpoint:
      url: ${NEXT_PUBLIC_DATOCMS_API_BASE}
      headers:
        accept: application/json
        authorization: ${NEXT_PUBLIC_DATOCMS_ACCESS_TOKEN}
        content-type: application/json
        x-exclude-invalid: 'true'
        x-include-drafts: 'true'
      introspect: true
