import React from 'react'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Link from 'next/link'

import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Mad til to',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang={'en'}>
      <body className={`${poppins.className} h-screen`}>
        <header>
          <div className={'container py-6'}>
            <Link href={'/'} className={'text-3xl font-bold text-red-600'}>
              Mad Til To
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
