import React from 'react'
import { motion } from "framer-motion"
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Link from 'next/link'

import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Mad til to',
  description: 'Generated by create next app',
}

const Path = (props: SVGPathElement) => (
    <motion.path
        fill={"transparent"}
        strokeWidth={"3"}
        stroke={"hsl(0, 0%, 18%)"}
        strokeLinecap={"round"}
        {...props}
    />
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang={'en'}>
      <body className={`${poppins.className} h-screen`}>
        <header className={'w-full border-b flex items-center'}>
          <div className={'container py-6'}>
            <Link href={'/'} className={'text-2xl md:text-3xl font-medium text-red-600'}>
              Mad Til To
            </Link>
            <button>

            </button>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
