import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

import './globals.css'

export const metadata: Metadata = {
  title: 'Mad til to',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang={'en'}>
      <body className={`${poppins.className} h-screen`}>
        <div className={'px-4 flex flex-col mx-auto'}>
          <header>
            <h1 className={'text-3xl font-bold text-red-600 '}>Mad Til To</h1>
          </header>
          {children}
        </div>
      </body>
    </html>
  )
}
